import "./globals.css";
import { poppins } from "./fonts";
import { Provider } from "@/utils/Provider/Provider";
import Navbar from "@/components/Shared/Navbar/Navbar";
import Footer from "@/components/Shared/Footer/Footer";
import TopHeader from "@/components/Shared/TopHeader/TopHeader";



export const metadata = {
  title: "Fast Business Loans – Solar Capital Group",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en" className="bg-[#ffffff] text-[#000000]">
      <body className={`${poppins.className}`}>

        <Provider>
          <header>
            <TopHeader />
            <nav className="nav">
              <Navbar />
            </nav>
          </header>


          <main>
            {children}
          </main>

          <footer>
            <Footer />
          </footer>
        </Provider>

      </body>
    </html>
  );
}
